# Default values for oval-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: perpetuumprogress/oval-subgraph
  pullPolicy: Always
  # Set environment variables
  env:
    - name: "POSTGRES_HOST"
      value: "postgres"
    - name: "POSTGRES_USER"
      value: "graph-node"
    - name: "POSTGRES_PASS"
      value: "let-me-in"
    - name: "POSTGRES_DB"
      value: "graph-node"
    - name: "IPFS"
      value: "ipfs:5001"
    - name: "ETHEREUM"
      value: "mumbai:https://polygon-mumbai-bor.publicnode.com"
    - name: "RUST_LOG"
      value: "INFO"
    # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "dev-oval-subgraph-run-service-account"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/enable-cors: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: graph.dev.oval.pepro.io
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - secretName: dev-oval-subgraph-tls
      hosts:
         - graph.dev.oval.pepro.io

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
