name: dev-cicd
on:
  push:
    branches:
      - 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'dev'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/oval-subgraph:dev
  deployment:
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: Prep helm chart
        run: |
          mv ./oval-chart/graph-node/Chart.yaml ./oval-chart/graph-node/Chart.old.yaml &&
          cat ./oval-chart/graph-node/Chart.old.yaml | grep -v appVersion > ./oval-chart/graph-node/Chart.yaml &&
          echo -e "\r\nappVersion: v${GITHUB_REF##*/}\r\n" >> ./oval-chart/graph-node/Chart.yaml &&
          cat ./oval-chart/graph-node/Chart.yaml &&
          mv ./oval-chart/postgres/Chart.yaml ./oval-chart/postgres/Chart.old.yaml &&
          cat ./oval-chart/postgres/Chart.old.yaml | grep -v appVersion > ./oval-chart/postgres/Chart.yaml &&
          echo -e "\r\nappVersion: v${GITHUB_REF##*/}\r\n" >> ./oval-chart/postgres/Chart.yaml &&
          cat ./oval-chart/postgres/Chart.yaml &&
          mv ./oval-chart/ipfs/Chart.yaml ./oval-chart/ipfs/Chart.old.yaml &&
          cat ./oval-chart/ipfs/Chart.old.yaml | grep -v appVersion > ./oval-chart/ipfs/Chart.yaml &&
          echo -e "\r\nappVersion: v${GITHUB_REF##*/}\r\n" >> ./oval-chart/ipfs/Chart.yaml &&
          cat ./oval-chart/ipfs/Chart.yaml
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
            helm upgrade dev-postgres-oval ./oval-chart/postgres --install --wait --atomic --namespace=dev-oval --set=app.name=dev_postgres_oval --values=./oval-chart/postgres/dev-values.yaml &&
            helm upgrade dev-ipfs-oval ./oval-chart/ipfs --install --wait --atomic --namespace=dev-oval --set=app.name=dev_ipfs_oval --values=./oval-chart/ipfs/dev-values.yaml &&
            helm upgrade dev-subgraph-oval ./oval-chart/graph-node --install --wait --atomic --namespace=dev-oval --set=app.name=dev_subgraph_oval --values=./oval-chart/graph-node/dev-values.yaml
          kubeconfig: '${{ secrets.DEV_KUBECONFIG }}'
